{{- if eq .Values.persistence.pvcOrHostPath "pvc" }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistence.pvc.name }}-pvc
spec:
  accessModes:
{{ toYaml .Values.persistence.pvc.accessModes | indent 4 }}
  {{- if and (.Values.persistence.pvc.storageClassName) (not (empty .Values.persistence.pvc.storageClassName)) }}
  storageClassName: "{{ .Values.persistence.pvc.storageClassName }}"
  {{- end  }}
  resources:
    requests:
      storage: "{{ .Values.persistence.pvc.size }}"
{{- end }}
