deployment:
    name: linux-monitor 
    
image:
  name: schnitz81/linux-monitor
  tag: latest
  pullPolicy: Always

container:
  backupMountpath: /backups

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 125m
    memory: 512Mi

persistence:
  # choose "pvc" or "hostPath" for persistent db storage.
  # Anything else to disable DB persistence and graph history will restart every time the pod is terminated.
  pvcOrHostPath: pvc 

  pvc:  
    name: linux-monitor-persistent 
    accessModes:
      - ReadWriteOnce
    size: 1Gi
    storageClassName: ""  # leave empty to use default StorageClass
  
  hostPath: 
    name: linux-monitor-persistent
    path: /backups  # persistence path on the host 
    containerPath: /backups  # same as persistence_path in the app config 

configfiles:
  config: |-
    client_port = 12345
    db_path = "/run"
    persistence_path = "/backups"
    html_path = "/run/linux-monitor"
    scancycletime = 10
    clientfile = "clients.conf"
  clients: |-
    # List of clients to monitor
    # {name} {IP address}
    hostname X.X.X.X	# <--------------- enter your own clients

webserver:
  containerport: 80
  exposeport: 80
  contentpath: "/run/linux-monitor"  # should be same as html_path

service:
  type: LoadBalancer 
  loadBalancerIP: ""
  clusterIP: ""
  nodePort: ""
  sessionAffinity: None
